# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
---
##
# Delete contents of redis cluster
##

- hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: flush elasticache of all content
      redis: command=flush flush_mode=all login_host="{{redis_master}}"
      register: results

    - debug: var=results

