# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
# kill instance that does not have yam, assumes executors are on machine
# kill jvm which includes jvm_class_name and spark_class_name

# cannot think of a more graceful way to share shutdown has already occurred
- set_fact: skip_machine_kill=false
- name: "skip entire block if previously set by another host"
  set_fact: skip_machine_kill=true
  with_inventory_hostnames: yarn-slaves
  when: hostvars[item]['machine_shutdown_target'] is defined
- debug: var=skip_machine_kill

# note in Ansible 2.2 will have a break feature.
# https://github.com/ansible/ansible/issues/1476

- block:
  - name: get process id of jvm {{jvm_class_name}}
    shell: "{{jps_command}}  -mlv | grep '{{jvm_class_name}}' | grep '{{spark_class_name}}'| awk '{ print $1 }'"
    register: result
    become: true
    become_user: spark
  - debug: var=result

  - name: "machine_shutdown_target is {{inventory_hostname}} when YAM not found"
    set_fact: machine_shutdown_target="{{inventory_hostname}}"
    when: result.stdout == ""

  # todo- can make sure executors are running. can be assumed currently

  - name: "shutdown machine"
    include: shutdown-machine-instance.yml
    when: machine_shutdown_target is defined

  when: not skip_machine_kill
