# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
---
- hosts: localhost
  sudo: no
  vars:
    # parameters sent from jenkins
    # kcl_ami_id:
    # worker_instance_type: c4.xlarge default
    # region:
    # kcl_group_name: "dev"

    # override in extra vars in jenkins if desired, these are defaults
    launch_count: 1
    instance_profile_name: app-kcl

  tasks:
    - include_vars: "group_vars/{{region}}"
    # has to be modified to launch based on whether instances are already created
    - name: Launch brand new ec2 instance
      ec2:
        # keypair is going to be devops as part of the baked ami
        key_name: "{{key_pair_name}}"
        instance_type: "{{worker_instance_type}}"
        image: "{{kcl_ami_id}}"
        wait: yes
        count: "{{launch_count}}"
        monitoring: yes
        group_id: "{{kcl_security_group_id}}"
        region: "{{region}}"
        vpc_subnet_id: "{{kcl_subnet_id}}"
        private_ip: "{{member_private_ip}}"
        # this must be yes because we are accessing internet WITHOUT NAT so we are not subject to this bottleneck!
        assign_public_ip: yes
        instance_profile_name: "{{instance_profile_name}}"
        instance_tags:
          Name: "{{kcl_group_name}} Kinesis Client {{member_private_ip}}"
          KCL_GROUP: "{{kcl_group_name}}"
          APP_ID: "KINESIS_PRODUCER"
      register: ec2

    - name: Wait for SSH to come up
      wait_for: host="{{ member_private_ip }}" port=22 delay=60 timeout=320 state=started



