# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
---
- hosts: localhost
  sudo: no
  vars:
    #
    # launch an instance that is not part of the private VPC in us-east-1
    #
    # parameters sent from jenkins:
    # kcl_ami_id:
    # worker_instance_type: m3.xlarge default
    # region:
    # kcl_group_name: "dev"

    # override in extra vars in jenkins if desired, these are defaults
    launch_count: 1
    instance_profile_name: app-kcl

  tasks:
    - include_vars: "group_vars/{{region}}"
    # has to be modified to launch based on whether instances are already created
    - name: Launch brand new ec2 instance
      ec2:
        # keypair is going to be devops as part of the pre-baked ami from the us-east region
        instance_type: "{{worker_instance_type}}"
        image: "{{kcl_ami_id}}"
        wait: yes
        count: "{{launch_count}}"
        monitoring: yes
        group: "{{kcl_security_group}}"
        region: "{{region}}"
        vpc_subnet_id: "{{kcl_subnet_id}}"
        # no other way for jenkins to run ansible against these which are in a different region.
        assign_public_ip: yes
        instance_profile_name: "{{instance_profile_name}}"
        instance_tags:
          Name: "{{kcl_group_name}} Kinesis Client"
          KCL_GROUP: "{{kcl_group_name}}"
          APP_ID: "KINESIS_PRODUCER"
      register: ec2

    - name: Wait for SSH to come up
      wait_for: host="{{ item.public_ip }}" port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances



