# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT

- apt: name=nginx state=installed
- name: copy over default site opening up zeppelin dir
  copy: src="files/{{item}}" dest="/{{item}}"
  with_items:
    - "etc/nginx/sites-enabled/default"

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
