# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
---
- hosts: all
  become: yes
  vars:
    default_timezone: PST8PDT

  ## TODO need to remove all usages to config-linux-base
  tasks:
  - name: upgrade all packages
    yum: name=* state=latest

  - include: update-hostfile.yml

  - name: set local time after yum update to default time zone
    shell: "sudo rm /etc/localtime; sudo ln -s /usr/share/zoneinfo/{{timezone|default(default_timezone)}}  /etc/localtime"
