# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
# modified from https://github.com/AerisCloud/ansible-disk/blob/master/tasks/main.yml
# main change is to add pass no. and dump
#

- name: "Install parted"
  package:
    name: parted
    state: present
  when: disk_additional_disks

- name: "Get disk alignment for disks"
  shell: |
    if
      [[ -e /sys/block/{{ item.disk | basename }}/queue/optimal_io_size && -e /sys/block/{{ item.disk | basename }}/alignment_offset && -e /sys/block/{{ item.disk | basename }}/queue/physical_block_size ]];
    then
      echo $[$(( ($(cat /sys/block/{{ item.disk | basename }}/queue/optimal_io_size) + $(cat /sys/block/{{ item.disk | basename }}/alignment_offset)) / $(cat /sys/block/{{ item.disk | basename }}/queue/physical_block_size) )) | 2048];
    else
      echo 2048;
    fi
  args:
    creates: '{{ item.part | default(item.disk + "1") }}'
    executable: '/bin/bash'
  with_items: '{{ disk_additional_disks }}'
  register: disk_offset

- name: "Partition additional disks"
  shell: |
    if
        [ -b {{ item.disk }} ]
    then
        [ -b {{ item.part | default(item.disk + "1") }} ] || parted -a optimal --script "{{ item.disk }}" mklabel gpt mkpart primary {{ disk_offset.stdout|default("2048") }}s 100% && sleep 5 && partprobe {{ item.disk }}; sleep 5
    fi
  args:
    creates: '{{ item.part | default(item.disk + "1") }}'
    executable: '/bin/bash'
  with_items: '{{ disk_additional_disks }}'

- name: "Create filesystem on the first partition"
  filesystem:
    dev: '{{ item.part | default(item.disk + "1") }}'
    force: '{{ item.force|d(omit) }}'
    fstype: '{{ item.fstype }}'
    opts: '{{ item.fsopts|d(omit) }}'
  with_items: '{{ disk_additional_disks }}'

- name: "Disable periodic fsck on ext3 or ext4 formatted disks"
  shell: tune2fs -c0 -i0 {{ item.part | default(item.disk + "1") }}
  with_items: '{{ disk_additional_disks }}'
  when: "disk_additional_disks and ( item.fstype == 'ext4' or item.fstype == 'ext3' ) and item.disable_periodic_fsck|default(false)|bool"

- name: "Ensure the mount directory exists"
  file:
    path: '{{ item.mount }}'
    owner: '{{ item.user | default("root") }}'
    group: '{{ item.group | default("root") }}'
    state: directory
  with_items: '{{ disk_additional_disks }}'

- name: "Get UUID for partition"
  command: blkid -s UUID -o value {{ item.part | default(item.disk + "1") }}
  register: disk_blkid
  with_items: '{{ disk_additional_disks }}'
  changed_when: False

- name: "Mount additional disk"
  mount:
    name: '{{ item.0.mount }}'
    fstype: '{{ item.0.fstype }}'
    opts: '{{ item.0.mount_options|d(omit) }}'
    dump: '{{item.0.dump}}'
    passno: '{{item.0.pass_num}}'
    src: 'UUID={{ item.1.stdout }}'
    state: '{{ item.0.mount_state|d("mounted") }}'
  with_together:
    - '{{ disk_additional_disks }}'
    - '{{ disk_blkid.results }}'

- name: "Ensure the permissions are set correctly"
  file:
    path: '{{ item.mount }}'
    owner: '{{ item.user | default("root") }}'
    group: '{{ item.group | default("root") }}'
    state: directory
  with_items: '{{ disk_additional_disks }}'