# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
# installs version of cassandra as overridden by {{cassandra_version_override}}
# note do NOT fix ansible warnings to stick curl into get_url. These commands are lifted directly from:
# http://docs.datastax.com/en/cassandra/3.x/cassandra/install/installDeb.html
# and should be kept same as the original

- block:
  - set_fact: cassandra_version="{{cassandra_version_override|default(cassandra_version_default)}}"
  - name: "update datastax apt repo with {{cassandra_version}}"
    shell: "echo 'deb http://debian.datastax.com/datastax-ddc {{cassandra_version}} main' | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list"
 # deb http://some.debian.mirror/debian/ $distro main contrib non-free
 # jessie main  /etc/apt/sources.list,
  - shell: "curl -L https://debian.datastax.com/debian/repo_key | sudo apt-key add -"

  - name: install datastax-ddc cassandra
    shell: "apt-get update"
    # appears to be some issues over whether or not update_cache=yes runs the same as apt-get update. just to an update.
  - apt: name=datastax-ddc state=installed
  - name: disable service, we NEVER want auto start service since we need to run the seeds one at a time in the cluster
    service: name=cassandra state=stopped enabled=no
  - shell: "systemctl daemon-reload"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# old install for Amazon Linux and Cntos
- block:
  - name: update datastax yum repo
    template: src="templates/etc/yum.repos.d/datastax.repo" dest="/etc/yum.repos.d/"

  - name: install cassandra
    yum: name=datastax-ddc state=installed

  - name: on centos 07, we have to reload the definition
    shell: systemctl daemon-reload
  when: ansible_distribution != 'Debian' and ansible_distribution != 'Ubuntu'