# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
# queries YARN to see if
# must pass in variables
# yarn_master_ip
# spark_driver_class

# test locally with:
# ansible-playbook -i ../inventory/test_local_analytics -c local test_rest_json.yml

# fails when
#   1. URL not reachable (connection not reachable)
#   2. Driver in question is "FAILED" or "KILLED"
# populates target_yarn_success_status when successful

  # When YARN first starts up, URL returns blank {  "apps": null  }
  # this UGLY filter is until Ansible 2.0 more gracefully allows for tasks to be included
  - set_fact: yarn_admin_url="http://{{yarn_master_ip}}:8088/ws/v1/cluster/apps?state=RUNNING"
  - name: "Get list of RUNNING YARN apps from {{yarn_admin_url}} "
    uri: url="{{yarn_admin_url}}" body_format=json return_content=yes
    register: yarn_response
    until: yarn_response.json.apps is defined and yarn_response.json.apps.app is defined
                and yarn_response.content.find(spark_driver_class)>-1
    retries: "{{yarn_status_retries}}"
    delay: "{{yarn_status_delay_in_seconds}}"

  - set_fact: yarn_apps="{{yarn_response.json.apps.app}}"
  - debug: var=yarn_apps
    when: debug_level is defined and debug_level=="info"

  - debug: var=yarn_response
  - set_fact:
      target_tracking_url: "{{item['trackingUrl']}}"
      target_yarn_app_id: "{{item['id']}}"
    with_items: yarn_response.json.apps.app
    when: item.name==spark_driver_class

  #- debug: var=hostvars['localhost']
  - debug: var=target_yarn_app_id




