# Copyright 2018 Dematic, Corp.
# Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
---
- hosts: all
  become: yes

# to run locally:
# ansible-playbook -i /dematic/gitlab/devops-config/ansible/roles/spark/inventory/yarn-devops install-node-exporter.yml --private-key /dematic/keys/google/gcp-devops  -u devops

  tasks:
    - name: "install node-exporter"
      apt: name=prometheus-node-exporter state=installed update_cache=yes

    - name: "start node-exporter service"
      service: name=prometheus-node-exporter state=started enabled=yes

    - name: "log service status"
      shell: "sudo service prometheus-node-exporter status"
      register: results

    - debug: var=results


