# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT
# ansible-playbook -i /dematic/gitlab/devops-config/ansible/roles/kafka/inventory/kafka-devops-cluster install-kafka-manager.yml --private-key /dematic/keys/google/gcp-devops -u kafka

- name: first get artifacts locally from repo
  hosts: localhost
  tasks:


    - include: ../../../repo/tasks/download-artifact-from-maven-repo.yml static=yes
      vars:
        artifact_owner: kafka
        artifact_id: "kafka-manager"
        artifact_dest_dir:  "{{local_artifact_location}}"
        artifact_repo_group_id: "com.yahoo"
        artifact_target_version: "{{kafka_manager_version_only}}"
        artifact_repo_type: "release"
        artifact_dest_fqn: "{{local_artifact_location}}/{{kafka_mgr_download_version}}.zip"
        artifact_extension: "zip"
        artifact_classfier_suffix: ""
      ignore_errors: yes
    # maven plugin bug, even though the zip gets downloaded, there is an unnecessary secondary call to get the jar results in error.

- name: "Copy over jar file to clients"
  hosts: kafka-manager
  become: yes
  tasks:
    #- name: "prepare install dir {{install_dir}}"
    #  file: path="{{install_dir}}" state=directory owner=kafka
    # not sure why problematic on ubuntu

    - name: "remove old versions directories if any"
      file: path="{{install_dir}}/{{kafka_mgr_download_version}}" state=absent

    - name: "Copy over artifacts from local"
      copy:
        src: "{{local_artifact_location}}/{{kafka_mgr_zip_file}}"
        dest: "{{kafka_mgr_download_fqn}}"
        owner: "kafka"
        group: "kafka"
      with_items:
        - "{{kafka_mgr_download_version}}"

    - name: "unpack kafka manager dist"
      unarchive: src={{kafka_mgr_download_fqn}} dest={{install_dir}} copy=no creates=no owner=kafka

    - file: path="{{install_dir}}/{{kafka_mgr_download_version}}" state=directory owner=kafka group=kafka recurse=true
      become: yes

    - name: create symlink to /opt/kafka/kafka_manager_latest
      file: src="{{install_dir}}/{{kafka_mgr_download_version}}" dest="{{kafka_manager_dir}}" owner=kafka group=kafka state=link

    - name: remove zip file
      file: path={{kafka_mgr_download_fqn}} state=absent

