# Copyright 2018 Dematic, Corp.  # Licensed under the MIT Open Source License: https://opensource.org/licenses/MIT

- name: tune tcp/ip settings
  include: ../../roles/linux/tune-tcp-ip.yml

- name: update latest to profile.d
  copy: src="files/etc/profile.d" dest="/etc/profile.d"

- name: update with latest logback.xml
  copy: src="files/" dest="{{producer_client_location}}" owner="{{producer_client_user}}"
